# Generated by Django 6.0.3 on 2026-04-03 13:13

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=320)),
                ('overview', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='case_study/thumbnails/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='case_study/covers/')),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('my_role', models.CharField(blank=True, max_length=200)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('tools_used', models.CharField(blank=True, help_text='Comma-separated: Figma, Miro, Notion', max_length=300)),
                ('challenge', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('goal', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('process', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('solution', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('outcome', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('live_url', models.URLField(blank=True)),
                ('prototype_url', models.URLField(blank=True)),
                ('figma_url', models.URLField(blank=True)),
                ('read_time', models.PositiveIntegerField(default=1, help_text='Estimated reading time in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO/search.', max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='case_study/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='case_study.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Image',
                'verbose_name_plural': 'Case Study Images',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, help_text='Example: 40%, 12 interviews, 3 weeks', max_length=100)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='case_study.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Metric',
                'verbose_name_plural': 'Case Study Metrics',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_study/sections/')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='case_study.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Section',
                'verbose_name_plural': 'Case Study Sections',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
