# Generated by Django 6.0.3 on 2026-04-03 13:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='challenge',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='goal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='outcome',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='process',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='process'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='solution'),
        ),
    ]
