# Generated by Django 6.0.3 on 2026-04-04 16:07

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='LATEST ARTICLES', help_text='Small text shown above the main blog section heading.', max_length=100)),
                ('title_light', models.CharField(default='My Blog', help_text='First/light part of the blog section title.', max_length=100)),
                ('title_accent', models.CharField(default='For You', help_text='Second/accent part of the blog section title.', max_length=100)),
                ('max_items', models.PositiveIntegerField(default=3, help_text='Maximum number of featured blog posts to show in this section.')),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Section',
            },
        ),
        migrations.CreateModel(
            name='BrandLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='core/brands/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Brand Logo',
                'verbose_name_plural': 'Brand Logos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='INTERESTED?', help_text='Small text shown above the main contact heading.', max_length=100)),
                ('title_light', models.CharField(default="Let's", help_text='First/light part of the contact section title.', max_length=100)),
                ('title_accent', models.CharField(default='Connect!', help_text='Second/accent part of the contact section title.', max_length=100)),
                ('submit_button_text', models.CharField(default='Send', help_text='Text shown on the contact form submit button.', max_length=50)),
                ('footer_logo_text', models.CharField(default='RiJU', help_text='Footer logo/brand text shown in the bottom bar.', max_length=50)),
                ('footer_copyright_text', models.CharField(default='© 2026 Riju', help_text='Footer copyright text shown beside the footer logo.', max_length=100)),
                ('footer_credit_text', models.CharField(default='by Afroza Riju', help_text='Footer credit text shown in the bottom bar.', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('year', models.CharField(help_text='Year or label shown in the small badge, e.g. "2022".', max_length=20)),
                ('title', models.CharField(help_text='Experience item title, e.g. Product Manager.', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Short description shown under the experience item title.')),
            ],
            options={
                'verbose_name': 'Experience Item',
                'verbose_name_plural': 'Experience Items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='MY JOURNEY & TRACK RECORD', help_text='Small heading text shown above the main experience title.', max_length=150)),
                ('title_light', models.CharField(default='Tons Of', help_text='First/light part of the main experience heading.', max_length=100)),
                ('title_accent', models.CharField(default='Experiences', help_text='Second/accent part of the main experience heading.', max_length=100)),
                ('experience_image', models.ImageField(blank=True, help_text='Main image shown on the left side of the experience section.', null=True, upload_to='core/experience/')),
            ],
            options={
                'verbose_name': 'Experience Section',
                'verbose_name_plural': 'Experience Section',
            },
        ),
        migrations.CreateModel(
            name='ProjectsShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='SHOW CASE', help_text='Small text shown above the main heading.', max_length=100)),
                ('title_light', models.CharField(default='Discover', help_text='First/light part of the section title.', max_length=100)),
                ('title_accent', models.CharField(default='How I Work', help_text='Second/accent part of the section title.', max_length=100)),
                ('max_items', models.PositiveIntegerField(default=6, help_text='Maximum number of featured projects to display in this section.')),
            ],
            options={
                'verbose_name': 'Projects Showcase Section',
                'verbose_name_plural': 'Projects Showcase Section',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title_light', models.CharField(default='Clients', help_text='First/light part of the testimonials section heading.', max_length=100)),
                ('title_accent', models.CharField(default='Talking', help_text='Second/accent part of the testimonials section heading.', max_length=100)),
                ('satisfaction_rate', models.CharField(default='100%', help_text='Satisfaction metric shown on the right side, e.g. "100%".', max_length=20)),
                ('satisfaction_rate_label', models.CharField(default='Satisfaction Rate', help_text='Label for the satisfaction metric.', max_length=100)),
                ('repeat_order_rate', models.CharField(default='97%', help_text='Repeat order metric shown on the right side, e.g. "97%".', max_length=20)),
                ('repeat_order_label', models.CharField(default='Repeat Order', help_text='Label for the repeat order metric.', max_length=100)),
                ('google_review_rating', models.CharField(default='4.8', help_text='Google review rating shown on the right side, e.g. "4.8".', max_length=20)),
                ('google_review_label', models.CharField(default='Google Review', help_text='Label for the Google review metric.', max_length=100)),
                ('hire_button_text', models.CharField(default='Hire Me', help_text='Text for the CTA button in the testimonials section.', max_length=50)),
                ('hire_button_link', models.CharField(default='#contact', help_text='Link for the CTA button in the testimonials section.', max_length=255)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='resume_file',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='secondary_button_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='secondary_button_text',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='awards',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='core/cv/'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='download_cv_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='download_cv_text',
            field=models.CharField(default='Download CV', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='hire_me_button_link',
            field=models.CharField(default='#contact', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='hire_me_button_text',
            field=models.CharField(default='Hire Me', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='show_play_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Short description shown under the skill title.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='number',
            field=models.CharField(blank=True, help_text='Optional custom display number, e.g. "01.". Leave blank to generate from order in frontend.', max_length=10),
        ),
        migrations.AddField(
            model_name='skill',
            name='project_link',
            field=models.CharField(blank=True, default='#', help_text='Link for the skill action button, e.g. portfolio/project section URL.', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='project_link_text',
            field=models.CharField(default='See Past Work', help_text='Button/link text shown at the bottom of the skill card.', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='Skill title shown in the skills card, e.g. UI Design.', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='completed_projects',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='happy_clients',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Main about heading, e.g. Product Designer with 3 Years Of Experience', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='ABOUT ME', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='availability_text',
            field=models.TextField(blank=True, help_text='Main descriptive text shown under the contact heading.'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(help_text='Primary contact email shown on the left side of the section.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='location',
            field=models.CharField(blank=True, help_text='Optional location text if needed later.', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary phone number shown on the left side of the section.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Optional WhatsApp number for contact purposes.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Internal admin note for this contact message.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='budget',
            field=models.CharField(blank=True, help_text='Optional project budget.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='company_name',
            field=models.CharField(blank=True, help_text='Optional company name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(help_text='Sender email address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(blank=True, help_text='Sender full name from the contact form.', max_length=120),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Marks whether the message has been read by admin.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(help_text='Main message content from the contact form.'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Sender phone number.', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(blank=True, help_text='Selected service/interest type from the contact form.', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the message was replied to.', null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed')], default='new', help_text='Admin workflow status of the contact message.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(help_text='Generated or custom subject for the contact message.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='full_name',
            field=models.CharField(help_text='Main highlighted name in the hero section.', max_length=120),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='greeting',
            field=models.CharField(default="Hi, I'm", help_text='Small greeting text shown above the hero title.', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_link',
            field=models.CharField(default='#contact', help_text='Link for the primary CTA button.', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(default='Get Start', help_text='Text for the circular CTA button.', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profession',
            field=models.CharField(help_text='Second line of hero title, e.g. Product Designer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image shown on the right side of hero section.', null=True, upload_to='core/hero/'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('dribbble', 'Dribbble'), ('facebook', 'Fb'), ('instagram', 'Ig'), ('behance', 'Be'), ('linkedin', 'In'), ('youtube', 'Ytb'), ('twitter', 'Twitter'), ('github', 'GitHub')], help_text='Social platform name shown in the footer social links.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(help_text='Full social profile URL.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_company',
            field=models.CharField(blank=True, help_text='Optional client company name shown after the role.', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(help_text='Client name shown in the testimonial card.', max_length=120),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=models.ImageField(blank=True, help_text='Client photo shown in the testimonial card.', null=True, upload_to='core/testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_role',
            field=models.CharField(blank=True, help_text='Client role/designation shown under the client name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as featured testimonial if needed for frontend filtering later.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, help_text='Client rating value from 1 to 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='review',
            field=models.TextField(help_text='Testimonial/review text shown in the card.'),
        ),
    ]
