# Generated by Django 6.0.3 on 2026-04-03 12:41

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='value',
            field=models.CharField(blank=True, help_text='Example: 40%, 12K+, 3 Weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
