# Generated by Django 6.0.3 on 2026-04-06 14:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_clint_name_project_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='clint_name',
            new_name='client_name',
        ),
        migrations.AddField(
            model_name='project',
            name='challenge',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Content'),
        ),
    ]
