# Generated by Django 6.0.3 on 2026-04-06 14:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_clint_name_project_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='challenge',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='challenge'),
        ),
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='goal'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcome',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='outcome'),
        ),
        migrations.AlterField(
            model_name='project',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='project',
            name='process',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='process'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='solution'),
        ),
    ]
